[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "cryptography>=45.0.5",
    "flask>=3.1.1",
    "pillow>=11.3.0",
    "playwright>=1.54.0",
    "pytz>=2025.2",
    "tkcalendar>=1.6.1",
]
